// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2bQlvDDL_zlQ1ZAyP0Cq_kRnjlUhEq6s',
    appId: '1:681089735002:web:ca9a1781a7893444093b63',
    messagingSenderId: '681089735002',
    projectId: 'rmclrs',
    authDomain: 'rmclrs.firebaseapp.com',
    storageBucket: 'rmclrs.appspot.com',
    measurementId: 'G-PMXPSF6Q1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6bTqBAjWKazYmknTMLE_JzM8EN0WowSg',
    appId: '1:681089735002:android:e0908d7c6c16febf093b63',
    messagingSenderId: '681089735002',
    projectId: 'rmclrs',
    storageBucket: 'rmclrs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4TKCSbvxoLtDWGxMgwQ8fNzc4-ZbZr4',
    appId: '1:681089735002:ios:a0ec6d422a6596ea093b63',
    messagingSenderId: '681089735002',
    projectId: 'rmclrs',
    storageBucket: 'rmclrs.appspot.com',
    iosBundleId: 'com.example.ff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf4TKCSbvxoLtDWGxMgwQ8fNzc4-ZbZr4',
    appId: '1:681089735002:ios:a0ec6d422a6596ea093b63',
    messagingSenderId: '681089735002',
    projectId: 'rmclrs',
    storageBucket: 'rmclrs.appspot.com',
    iosBundleId: 'com.example.ff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2bQlvDDL_zlQ1ZAyP0Cq_kRnjlUhEq6s',
    appId: '1:681089735002:web:abe5ae1324b4d246093b63',
    messagingSenderId: '681089735002',
    projectId: 'rmclrs',
    authDomain: 'rmclrs.firebaseapp.com',
    storageBucket: 'rmclrs.appspot.com',
    measurementId: 'G-WTG96DSX9K',
  );
}
